---

- name: Download and install elasticsearch gpg public signing key
  apt_key:
    url:   "{{ elasticsearch_signing_key_url }}"
    state: present

- name: Add elasticsearch apt repository definition to apt sources list
  apt_repository:
    repo:         "{{ elasticsearch_apt_repo }}"
    update_cache: yes
    state:        present
  when: elasticsearch_major_version|int >= 5

- name: Install elasticsearch
  apt: 
    name:  "elasticsearch={{ elasticsearch_version|default('*') }}"
    state: present
